#!/usr/bin/env python
# -*- coding: utf-8 -*-

[database]
host: 
databaseName: 
username: 
password: 


[twitter]
accountNames:  ; use comma seperation for several items
consumerKey: 
consumerSecret: 
accessToken: 
accessTokenSecret: 


[github]
# Switch to organization context, click on "News Feed" and copy the token:
# https://github.com/organizations/hickerspace/basti2342.private.atom?token=THIS_IS_THE_TOKEN
token: 

[soup]
# Go to http://www.soup.io/notifications, click on "RSS-Feed" an copy the token:
# http://www.soup.io/notifications/THIS_IS_THE_TOKEN.rss
token: 

[mailman]
lists:  ; use comma seperation for several items
weburl: 
loginMailAddress: 
loginPassword: 
